export const APP_ROUTES = {
  HOME: '/',
  EXPLORE: '/explore',
  AD_DETAILS: '/ads/:slug',
  CATEGORY_PAGE: '/categories/:slug',
  CITY_PAGE: '/cities/:slug',
  PACKAGES: '/packages',
  FAQ: '/faq',
  CONTACT: '/contact',
  TERMS: '/terms',
  PRIVACY: '/privacy',
  LEGAL: '/legal',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',

  CLIENT_DASHBOARD: '/client/dashboard',
  CLIENT_ADS: '/client/ads',
  CLIENT_ADS_NEW: '/client/ads/new',
  CLIENT_PAYMENTS: '/client/payments',
  CLIENT_NOTIFICATIONS: '/client/notifications',

  MODERATOR_QUEUE: '/moderator/review-queue',
  MODERATOR_FLAGS: '/moderator/flags',
  MODERATOR_HISTORY: '/moderator/history',

  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_PAYMENTS: '/admin/payments',
  ADMIN_ADS: '/admin/ads',
  ADMIN_PACKAGES: '/admin/packages',
  ADMIN_CATEGORIES: '/admin/categories',
  ADMIN_CITIES: '/admin/cities',
  ADMIN_USERS: '/admin/users',
  ADMIN_ANALYTICS: '/admin/analytics',
  ADMIN_SYSTEM_HEALTH: '/admin/system-health',
  ADMIN_TRACEABILITY: '/admin/traceability',
}
